// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyyvbdupignelffeqkzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eXZiZHVwaWduZWxmZmVxa3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDU3NTMsImV4cCI6MjA1NjgyMTc1M30.VEHKJY-neWCPViiv5kleY4RKHggIMK-mmwyuWqJvM2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);